### PR TITLE
Added distinct operator and tests to cover its logic

### PR DESCRIPTION
**Pull request by sergdort**
#21

### CODE REVIEW

**Comment by fpillet** [comment]
Fantastic, thanks serg! 

Just one comment, I personally tend to stay away from objc_sync_enter / objc_sync_exit. I didn't even know they worked with non-ObjC objects!

**Comment by sergdort** [comment]
Hi, @fpillet, do you think I would be better to use NSLock instead?

**Comment by fpillet** [comment]
It would be cleaner I think, maybe ask @kzaher what he thinks about it?

**Comment by kzaherRH** [comment]
You don't need locks here

```
    public func distinct() -> Observable<Element> {
 +        var cache = [Element]()
 +        return flatMap { element -> Observable<Element> in
 +            objc_sync_enter(self); defer {objc_sync_exit(self)}
 +            if cache.contains(element) {
 +                return Observable<Element>.empty()
 +            } else {
 +                cache.append(element)
 +                return Observable<Element>.just(element)
 +            }
 +        }
 +    }
```

There is no concurrency since this is a single sequence.

**Pull request merged**
